### ISSUE TITLE
[Bug] Restarting the game erases FTBChunks info slot setting

### ISSUE THREAD

**Issue by DedMaxim** [frank89722/JourneyMapIntegration#29]
Client settings like FTB Chunks overlay button or FTB Chunks info slot are, either not saved or loaded correctly after the game is restarted and default values are restored.
Video demonstration:
https://drive.google.com/file/d/1Fl6UO1VvnU7Kg5QyAAVTydH40JkBbxyI/view?usp=sharing

Environment:
Intel Xeon E5-2680v2
Nvidia GTX 1070
4x8Gb DDR3 ECC REG RAM
Windows 10 22H2

Minecraft 1.20.1
Forge 47.2.20
Architectury 9.2.14
FTB Chunks 2001.2.7
FTB Library 2001.1.5
FTB Teams 2001.2.0
Journeymap 5.9.20
JMI 0.14-45

**Comment by frank89722** [comment]
I have did some tests and found out this might be an issue in Journeymap
https://github.com/TeamJM/journeymap/issues/692

**Comment by frank89722** [comment]
Should be fixed in v1.20.1-0.14-48
thank you for the bug report!

**Comment by DedMaxim** [comment]
The bug is still partially present. Now the game doesn't forget settings after re-joining the world/server but still does after restarting the whole game

Video https://drive.google.com/file/d/1DojfVVPWj8yfqTsE1vmKdLaJPcVYjezI/view?usp=sharing

**Comment by frank89722** [comment]
> The bug is still partially present. Now the game doesn't forget settings after re-joining the world/server but still does after restarting the whole game
> 
> Video https://drive.google.com/file/d/1DojfVVPWj8yfqTsE1vmKdLaJPcVYjezI/view?usp=sharing

That's is not a bug, that's how it works for now
