### ISSUE TITLE
[1.18.1] Latest version (0.5-27) crashes on startup.

### ISSUE THREAD

**Issue by Gbergz** [frank89722/JourneyMapIntegration#4]
Title^

Game crashes when trying to load the game with the latest version released.

I'm using the defaultconfig config option, just to note that.

**Crash-Report**: https://gist.github.com/Gbergz/1adb13a03c70c108565375abe83055d1

Versions:
Forge: 39.0.10
Minecraft: 1.18.1
Journey Map: 5.8.0beta6
Integration: 0.5.-27

**-** Gbergz

**Comment by frank89722** [comment]
Oops..
Should be fixed in 0.5.-28

**Comment by Gbergz** [comment]
Still getting crashes on 0.5-28
https://gist.github.com/Gbergz/588f972787eff633a4bcf927f810e2cb

**Comment by frank89722** [comment]
Can confirm it's fixed this time.
https://www.curseforge.com/minecraft/mc-mods/journeymap-integration/files/3599605

Thank's your report!
